name: Generate Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: Vitor-Izidoro
          svg_out_path: dist/github-snake.svg

      - name: Commit and Push if Changes
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add dist/github-snake.svg
            git commit -m "Generate Snake"
            git push origin main
          else
            echo "No changes to commit"
